/**
 * Comprehensive Itinerary Seed Script
 *
 * This script populates all missing itinerary data for trekking routes
 * and safari packages in the Prisma PostgreSQL database.
 *
 * Usage: npx tsx scripts/seed-itineraries.ts
 */

import { PrismaClient } from "@prisma/client";
import { config } from "dotenv";

// Load environment variables
config({ path: ".env.local" });

const accelerateUrl = process.env.DATABASE_URL_ACCELERATE;
if (!accelerateUrl) {
  throw new Error("DATABASE_URL_ACCELERATE not set");
}

const prisma = new PrismaClient({ accelerateUrl });

// ============================================
// TREKKING ROUTES ITINERARY DATA
// ============================================

const trekkingItineraries: Record<string, {
  day: number;
  title: string;
  description: string;
  elevation?: string;
  distance?: string;
  duration?: string;
  camp?: string;
  meals?: string;
}[]> = {
  // 7 Days Machame Route (extracted from WordPress)
  "7-days-machame-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Upon arrival, you will be picked up from Kilimanjaro Airport and transferred to Arusha Planet Lodge in Arusha, a journey of approximately 50 minutes. This lodge features comfortable beds, a beautiful garden, a swimming pool, and excellent meals. Our mountain guides will meet you at the lodge for a pre-trek briefing, during which they will check your gear and discuss other logistics for your upcoming adventure.",
      elevation: "1,400m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Machame Gate to Machame Camp",
      description: "In the morning, our team will pick you up at the lodge and transfer you to Machame Park Gate, which takes about 2 hours. Upon arrival and after registration, you will begin your slow ascent through the dense rainforest to Machame Hut Campsite. Along the way, keep an eye out for black-and-white Colobus monkeys, blue monkeys, and a variety of beautiful birds. The stunning scenery, characterized by lush greenery and towering trees, makes this route truly unique.",
      elevation: "1,800m → 3,000m",
      distance: "11km",
      duration: "5-6 hours",
      camp: "Machame Camp (3,000m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Machame Camp to Shira Cave Camp",
      description: "In the morning, after breakfast with packed picnic lunches, we will continue our journey to Shira Cave Campsite. The day promises clear skies as we walk through the heather and moorland zone. Today's trail is a bit steep, allowing for stunning views of both Shira Peak and Kibo. You'll also catch a perfect glimpse of Mount Meru in Arusha.",
      elevation: "3,000m → 3,840m",
      distance: "5km",
      duration: "4-5 hours",
      camp: "Shira Cave Camp (3,840m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Shira Cave to Barranco Camp via Lava Tower",
      description: "In the morning, after breakfast with packed picnic lunches, we will continue our trek along the eastern side facing Kibo Peak. The day will be cool as we cross into the alpine desert. We will enjoy a picnic lunch at Lava Tower, situated at 4,600 meters. After lunch, we will descend to Barranco Camp. This 'climb high, sleep low' approach aids acclimatization.",
      elevation: "3,840m → 4,630m → 3,960m",
      distance: "10km",
      duration: "6-7 hours",
      camp: "Barranco Camp (3,960m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Barranco Camp to Karanga Camp",
      description: "In the morning, after breakfast, we will continue our ascent along a steep ridge up the adventurous Barranco Wall to Karanga Camp. This day offers an impressive view of visitors and porters navigating the challenging terrain while carrying their loads. Some areas will require climbing, but after conquering the Barranco Wall, you'll reach the top and have the opportunity to relax and take photos of Kibo Peak, with its beautiful glaciers gracing the southern side. After lunch, you'll embark on a short acclimatization walk.",
      elevation: "3,960m → 4,035m",
      distance: "5km",
      duration: "3-4 hours",
      camp: "Karanga Camp (4,035m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Karanga Camp to Barafu Camp",
      description: "In the morning, after breakfast with packed picnic lunches, we will continue our journey to Barafu Camp, traversing the stunning alpine desert. The trek to Barafu Camp will take approximately 2-3 hours, offering you the chance to enjoy the unique landscape and prepare for the next stage of your adventure. Rest well and prepare for summit night.",
      elevation: "4,035m → 4,673m",
      distance: "4km",
      duration: "2-3 hours",
      camp: "Barafu Camp (4,673m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 6,
      title: "Summit Day - Uhuru Peak",
      description: "At midnight, after enjoying refreshing tea and cookies, we will begin our ascent to the summit. This day can be challenging as you strive to make your dream of reaching the summit a reality. The trek to Uhuru Peak, standing at 5,895 meters, will take approximately 6-7 hours. Once at the summit, you'll have about 20 minutes to take photos and savor the breathtaking views. After your time at the summit, we will begin our descent to Mweka Camp via Barafu Camp.",
      elevation: "4,673m → 5,895m → 3,100m",
      distance: "16km",
      duration: "12-16 hours",
      camp: "Mweka Camp (3,100m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 7,
      title: "Mweka Camp to Mweka Gate",
      description: "The morning after breakfast, descend to Mweka Park Gate through a beautiful rainforest for about 3-4 hours. After checking out of the Park, receive your summit certificates. Meet our vehicle and transfer to Arusha City for 2 hours. Overnight at Arusha Planet Lodge. Day 8, our driver will pick you up at the lodge and transfer you to the Airport for your flight home.",
      elevation: "3,100m → 1,640m",
      distance: "10km",
      duration: "3-4 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 6 Days Machame Route
  "6-days-machame-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrival at Kilimanjaro International Airport. Transfer to your hotel in Moshi/Arusha for briefing and gear check with your guide team.",
      elevation: "1,400m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Machame Gate to Machame Camp",
      description: "After breakfast, drive to Machame Gate (1,800m) for registration. Begin trekking through lush rainforest, home to Colobus monkeys and exotic birds. The trail is well-maintained but can be muddy. Arrive at Machame Camp in the late afternoon.",
      elevation: "1,800m → 3,000m",
      distance: "11km",
      duration: "5-6 hours",
      camp: "Machame Camp (3,000m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Machame Camp to Shira Camp",
      description: "Trek through the moorland zone with stunning views of Kibo Peak. The vegetation changes from forest to heather and giant groundsels. Arrive at Shira Plateau, an ancient volcanic caldera.",
      elevation: "3,000m → 3,840m",
      distance: "5km",
      duration: "4-5 hours",
      camp: "Shira Camp (3,840m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Shira Camp to Barranco Camp via Lava Tower",
      description: "Ascend towards Lava Tower (4,630m) for acclimatization, then descend to Barranco Camp. This 'climb high, sleep low' technique is crucial for preventing altitude sickness.",
      elevation: "3,840m → 4,630m → 3,960m",
      distance: "10km",
      duration: "6-7 hours",
      camp: "Barranco Camp (3,960m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Barranco Camp to Barafu Camp",
      description: "Climb the famous Barranco Wall, a challenging but rewarding scramble. Continue through Karanga Valley to Barafu Camp, your summit base. Rest and prepare for the midnight summit attempt.",
      elevation: "3,960m → 4,673m",
      distance: "9km",
      duration: "7-8 hours",
      camp: "Barafu Camp (4,673m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Summit Day - Uhuru Peak",
      description: "Begin summit attempt around midnight. Trek through Stella Point to Uhuru Peak (5,895m) for sunrise at the Roof of Africa. Descend to Mweka Camp for overnight.",
      elevation: "4,673m → 5,895m → 3,100m",
      distance: "16km",
      duration: "12-16 hours",
      camp: "Mweka Camp (3,100m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 6,
      title: "Mweka Camp to Mweka Gate",
      description: "Final descent through the rainforest to Mweka Gate. Receive summit certificates and transfer to your hotel in Moshi/Arusha.",
      elevation: "3,100m → 1,640m",
      distance: "10km",
      duration: "3-4 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 8 Days Lemosho Route
  "8-days-lemosho-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro International Airport. Transfer to your hotel in Arusha for overnight stay, briefing, and gear check.",
      elevation: "1,400m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Londorossi Gate to Mti Mkubwa Camp",
      description: "Drive to Londorossi Gate on the western side of Kilimanjaro. After registration, continue driving to the trailhead at Lemosho Glades (2,100m). Begin trekking through pristine montane forest, rich in wildlife including Colobus monkeys and tropical birds.",
      elevation: "2,100m → 2,750m",
      distance: "6km",
      duration: "3-4 hours",
      camp: "Mti Mkubwa Camp (2,750m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Mti Mkubwa to Shira 1 Camp",
      description: "Continue through rainforest before emerging onto the Shira Plateau. The vegetation transitions from forest to moorland with giant heathers. Enjoy spectacular views of Kibo Peak.",
      elevation: "2,750m → 3,500m",
      distance: "8km",
      duration: "5-6 hours",
      camp: "Shira 1 Camp (3,500m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Shira 1 to Shira 2 Camp",
      description: "Trek across the Shira Plateau, one of Africa's highest plateaus. Pass unique alpine vegetation including giant groundsels and lobelias. Optional acclimatization hike to Shira Cathedral.",
      elevation: "3,500m → 3,840m",
      distance: "6km",
      duration: "4-5 hours",
      camp: "Shira 2 Camp (3,840m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Shira 2 to Barranco Camp via Lava Tower",
      description: "Ascend towards Lava Tower (4,630m) for excellent acclimatization. Enjoy lunch at this dramatic volcanic formation before descending to Barranco Camp through the alpine desert zone.",
      elevation: "3,840m → 4,630m → 3,960m",
      distance: "10km",
      duration: "6-7 hours",
      camp: "Barranco Camp (3,960m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Barranco Camp to Karanga Camp",
      description: "Climb the spectacular Barranco Wall, a highlight of the route. This non-technical scramble rewards you with stunning views of the southern glaciers. Continue to Karanga Valley.",
      elevation: "3,960m → 4,035m",
      distance: "5km",
      duration: "4-5 hours",
      camp: "Karanga Camp (4,035m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 6,
      title: "Karanga Camp to Barafu Camp",
      description: "Short but steady climb to Barafu Camp, your summit base. The landscape becomes increasingly barren as you enter the arctic zone. Rest and prepare for summit night.",
      elevation: "4,035m → 4,673m",
      distance: "4km",
      duration: "3-4 hours",
      camp: "Barafu Camp (4,673m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 7,
      title: "Summit Day - Uhuru Peak",
      description: "Begin summit attempt around midnight. Trek through scree to Stella Point on the crater rim, then continue to Uhuru Peak (5,895m). Witness an unforgettable sunrise from the Roof of Africa. Descend to Mweka Camp.",
      elevation: "4,673m → 5,895m → 3,100m",
      distance: "16km",
      duration: "12-16 hours",
      camp: "Mweka Camp (3,100m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 8,
      title: "Mweka Camp to Mweka Gate",
      description: "Descend through rainforest to Mweka Gate. Receive summit certificates and tips ceremony with your crew. Transfer to hotel in Moshi/Arusha for celebration dinner.",
      elevation: "3,100m → 1,640m",
      distance: "10km",
      duration: "3-4 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 6 Days Marangu Route
  "6-days-marangu-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro International Airport. Transfer to your hotel in Moshi for briefing and equipment check.",
      elevation: "900m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Marangu Gate to Mandara Hut",
      description: "Drive to Marangu Gate (1,860m). After registration, begin trekking through beautiful rainforest. The well-maintained trail passes through forest rich in birdlife and Colobus monkeys. Arrive at Mandara Hut, the first sleeping hut with beds.",
      elevation: "1,860m → 2,720m",
      distance: "8km",
      duration: "3-4 hours",
      camp: "Mandara Hut (2,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Mandara Hut to Horombo Hut",
      description: "Leave the rainforest behind and enter the moorland zone. The trail offers stunning views of both Kibo and Mawenzi peaks. Pass through giant heather and groundsel vegetation.",
      elevation: "2,720m → 3,720m",
      distance: "12km",
      duration: "5-6 hours",
      camp: "Horombo Hut (3,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Acclimatization Day at Horombo",
      description: "Spend the day acclimatizing at Horombo Hut. Take a day hike towards Mawenzi Hut (4,600m) or explore the Zebra Rocks. This extra day significantly improves your summit success rate.",
      elevation: "3,720m → 4,200m → 3,720m",
      distance: "6-10km",
      duration: "4-5 hours",
      camp: "Horombo Hut (3,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Horombo Hut to Kibo Hut",
      description: "Trek across the lunar landscape of the alpine desert. The terrain becomes increasingly barren as you approach Kibo Hut, your summit base camp. Rest and prepare for the midnight summit attempt.",
      elevation: "3,720m → 4,700m",
      distance: "10km",
      duration: "5-6 hours",
      camp: "Kibo Hut (4,700m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Summit Day - Uhuru Peak",
      description: "Begin summit attempt around midnight. Climb through scree to Gilman's Point on the crater rim, then continue along the crater to Uhuru Peak (5,895m). Descend back to Horombo Hut.",
      elevation: "4,700m → 5,895m → 3,720m",
      distance: "21km",
      duration: "12-16 hours",
      camp: "Horombo Hut (3,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 6,
      title: "Horombo Hut to Marangu Gate",
      description: "Final descent through moorland and rainforest back to Marangu Gate. Receive your summit certificates and transfer to your hotel.",
      elevation: "3,720m → 1,860m",
      distance: "20km",
      duration: "5-6 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 5 Days Marangu Route
  "5-days-marangu-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro International Airport. Transfer to your hotel in Moshi for briefing and equipment check.",
      elevation: "900m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Marangu Gate to Mandara Hut",
      description: "Drive to Marangu Gate. Trek through rainforest to Mandara Hut, your first overnight stop with dormitory-style accommodation.",
      elevation: "1,860m → 2,720m",
      distance: "8km",
      duration: "3-4 hours",
      camp: "Mandara Hut (2,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Mandara Hut to Horombo Hut",
      description: "Ascend through moorland with views of Kibo and Mawenzi peaks. The landscape transforms from forest to alpine meadows.",
      elevation: "2,720m → 3,720m",
      distance: "12km",
      duration: "5-6 hours",
      camp: "Horombo Hut (3,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Horombo Hut to Kibo Hut",
      description: "Cross the saddle between Kibo and Mawenzi through alpine desert. Arrive at Kibo Hut and rest for the summit attempt.",
      elevation: "3,720m → 4,700m",
      distance: "10km",
      duration: "5-6 hours",
      camp: "Kibo Hut (4,700m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Summit Day - Uhuru Peak",
      description: "Midnight start for the summit. Reach Gilman's Point, then Uhuru Peak for sunrise. Long descent to Horombo Hut.",
      elevation: "4,700m → 5,895m → 3,720m",
      distance: "21km",
      duration: "14-18 hours",
      camp: "Horombo Hut (3,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Horombo Hut to Marangu Gate",
      description: "Descend through all vegetation zones back to Marangu Gate. Collect certificates and transfer to hotel.",
      elevation: "3,720m → 1,860m",
      distance: "20km",
      duration: "5-6 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 6 Days Rongai Route
  "6-days-rongai-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro International Airport. Transfer to hotel in Moshi for briefing and gear check.",
      elevation: "900m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Rongai Gate to Simba Camp",
      description: "Drive to Rongai Gate near the Kenyan border (about 3-4 hours). Trek through cultivated farmland then pine forest. The northern approach offers a different perspective of Kilimanjaro.",
      elevation: "1,950m → 2,625m",
      distance: "8km",
      duration: "3-4 hours",
      camp: "Simba Camp (2,625m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Simba Camp to Kikelewa Camp",
      description: "Continue through moorland with views of Mawenzi Peak. The trail is gentle and allows excellent acclimatization.",
      elevation: "2,625m → 3,630m",
      distance: "10km",
      duration: "5-6 hours",
      camp: "Kikelewa Camp (3,630m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Kikelewa Camp to Mawenzi Tarn Camp",
      description: "Ascend to Mawenzi Tarn, a beautiful alpine lake at the base of Mawenzi Peak. Afternoon acclimatization hike towards the peak.",
      elevation: "3,630m → 4,330m",
      distance: "5km",
      duration: "3-4 hours",
      camp: "Mawenzi Tarn Camp (4,330m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Mawenzi Tarn to Kibo Hut",
      description: "Cross the lunar landscape of the Saddle between Mawenzi and Kibo. Arrive at Kibo Hut and prepare for summit night.",
      elevation: "4,330m → 4,700m",
      distance: "8km",
      duration: "4-5 hours",
      camp: "Kibo Hut (4,700m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Summit Day - Uhuru Peak",
      description: "Midnight start for Uhuru Peak. Ascend via Gilman's Point. Descend via Marangu Route to Horombo Hut for variety.",
      elevation: "4,700m → 5,895m → 3,720m",
      distance: "21km",
      duration: "12-16 hours",
      camp: "Horombo Hut (3,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 6,
      title: "Horombo Hut to Marangu Gate",
      description: "Final descent through rainforest to Marangu Gate. Receive certificates and transfer to hotel.",
      elevation: "3,720m → 1,860m",
      distance: "20km",
      duration: "5-6 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 7 Days Rongai Route
  "7-days-rongai-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro International Airport. Transfer to hotel in Moshi/Arusha for briefing.",
      elevation: "900m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Rongai Gate to Simba Camp",
      description: "Drive to Rongai Gate on the northern slopes. Trek through farmland and pine forest to Simba Camp.",
      elevation: "1,950m → 2,625m",
      distance: "8km",
      duration: "3-4 hours",
      camp: "Simba Camp (2,625m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Simba Camp to Second Cave Camp",
      description: "Continue ascending through moorland. The path offers views of Kenya to the north and Mawenzi Peak.",
      elevation: "2,625m → 3,450m",
      distance: "8km",
      duration: "4-5 hours",
      camp: "Second Cave Camp (3,450m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Second Cave to Kikelewa Camp",
      description: "Trek through alpine meadows with spectacular views of both peaks. The gentle gradient aids acclimatization.",
      elevation: "3,450m → 3,630m",
      distance: "6km",
      duration: "3-4 hours",
      camp: "Kikelewa Camp (3,630m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Kikelewa Camp to Mawenzi Tarn",
      description: "Ascend to the stunning Mawenzi Tarn, nestled below the jagged Mawenzi Peak. Afternoon acclimatization walk.",
      elevation: "3,630m → 4,330m",
      distance: "5km",
      duration: "3-4 hours",
      camp: "Mawenzi Tarn Camp (4,330m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Mawenzi Tarn to Kibo Hut",
      description: "Cross the Saddle, an alpine desert between the two peaks. Rest at Kibo Hut before summit night.",
      elevation: "4,330m → 4,700m",
      distance: "8km",
      duration: "4-5 hours",
      camp: "Kibo Hut (4,700m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 6,
      title: "Summit Day - Uhuru Peak",
      description: "Midnight summit attempt via Gilman's Point to Uhuru Peak. Descend to Horombo Hut via the Marangu Route.",
      elevation: "4,700m → 5,895m → 3,720m",
      distance: "21km",
      duration: "12-16 hours",
      camp: "Horombo Hut (3,720m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 7,
      title: "Horombo Hut to Marangu Gate",
      description: "Descend through moorland and rainforest. Certificate ceremony at the gate and transfer to hotel.",
      elevation: "3,720m → 1,860m",
      distance: "20km",
      duration: "5-6 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 6 Days Umbwe Route
  "6-days-umbwe-route": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro Airport. Transfer to hotel for briefing on this challenging direct route.",
      elevation: "900m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Umbwe Gate to Umbwe Cave Camp",
      description: "Drive to Umbwe Gate. Begin steep ascent through dense rainforest along a ridge. This is the most direct and steepest route on Kilimanjaro.",
      elevation: "1,600m → 2,940m",
      distance: "10km",
      duration: "5-6 hours",
      camp: "Umbwe Cave Camp (2,940m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Umbwe Cave to Barranco Camp",
      description: "Continue the steep climb through moorland and then alpine desert. The route joins the Southern Circuit at Barranco.",
      elevation: "2,940m → 3,960m",
      distance: "6km",
      duration: "4-6 hours",
      camp: "Barranco Camp (3,960m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Barranco Camp to Karanga Camp",
      description: "Climb the Barranco Wall and traverse to Karanga Camp. Optional acclimatization walk in the afternoon.",
      elevation: "3,960m → 4,035m",
      distance: "5km",
      duration: "4-5 hours",
      camp: "Karanga Camp (4,035m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Karanga Camp to Barafu Camp",
      description: "Short but steady climb to the summit base camp. Rest and prepare for midnight summit attempt.",
      elevation: "4,035m → 4,673m",
      distance: "4km",
      duration: "3-4 hours",
      camp: "Barafu Camp (4,673m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 5,
      title: "Summit Day - Uhuru Peak",
      description: "Midnight start for Uhuru Peak. This challenging route rewards with spectacular crater views. Descend to Mweka Camp.",
      elevation: "4,673m → 5,895m → 3,100m",
      distance: "16km",
      duration: "12-16 hours",
      camp: "Mweka Camp (3,100m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 6,
      title: "Mweka Camp to Mweka Gate",
      description: "Descend through rainforest to Mweka Gate. Certificate ceremony and transfer to hotel.",
      elevation: "3,100m → 1,640m",
      distance: "10km",
      duration: "3-4 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 4 Days Mount Meru
  "4-days-mount-meru-climbing": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro Airport. Transfer to hotel in Arusha for briefing on Mount Meru climb.",
      elevation: "1,400m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Momella Gate to Miriakamba Hut",
      description: "Drive to Arusha National Park's Momella Gate. Trek through montane forest with armed ranger (for wildlife safety). Possible sightings of buffalo, giraffe, and Colobus monkeys.",
      elevation: "1,500m → 2,514m",
      distance: "10km",
      duration: "4-5 hours",
      camp: "Miriakamba Hut (2,514m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Miriakamba Hut to Saddle Hut",
      description: "Ascend through giant heather forest. Visit Elephant Ridge for views of the ash cone. Continue to Saddle Hut with stunning views of Kilimanjaro.",
      elevation: "2,514m → 3,566m",
      distance: "5km",
      duration: "3-4 hours",
      camp: "Saddle Hut (3,566m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Summit Day - Socialist Peak",
      description: "Pre-dawn start along the crater rim to Socialist Peak (4,566m). Spectacular sunrise views over Kilimanjaro and the Great Rift Valley. Return to Miriakamba Hut.",
      elevation: "3,566m → 4,566m → 2,514m",
      distance: "13km",
      duration: "8-10 hours",
      camp: "Miriakamba Hut (2,514m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 4,
      title: "Miriakamba Hut to Momella Gate",
      description: "Descend through the forest via the shorter route. Game viewing opportunities. Transfer to hotel in Arusha.",
      elevation: "2,514m → 1,500m",
      distance: "7km",
      duration: "2-3 hours",
      meals: "Breakfast, Lunch",
    },
  ],

  // 3 Days Ol Doinyo Lengai
  "3-days-2-nights-oldoinyo-lengai-climbing": [
    {
      day: 0,
      title: "Arrival Day",
      description: "Arrive at Kilimanjaro Airport. Transfer to hotel in Arusha for briefing on this unique active volcano climb.",
      elevation: "1,400m",
      meals: "Dinner",
    },
    {
      day: 1,
      title: "Arusha to Lengai Base Camp",
      description: "Drive through Maasai land to the base of Ol Doinyo Lengai, the 'Mountain of God' in Maasai language. Pass Lake Manyara and Lake Natron. Arrive at base camp and rest before midnight climb.",
      elevation: "1,400m → 1,700m",
      distance: "Drive 6-7 hours",
      duration: "6-7 hours drive",
      camp: "Lengai Base Camp (1,700m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 2,
      title: "Summit Ol Doinyo Lengai",
      description: "Begin climbing at midnight to avoid the heat. The ascent is steep and challenging on volcanic ash and scree. Reach the crater rim at sunrise to see the active carbonatite lava. Descend and rest at base camp.",
      elevation: "1,700m → 2,878m → 1,700m",
      distance: "8km",
      duration: "8-10 hours",
      camp: "Lengai Base Camp (1,700m)",
      meals: "Breakfast, Lunch, Dinner",
    },
    {
      day: 3,
      title: "Return to Arusha",
      description: "Optional visit to Lake Natron to see flamingos. Drive back to Arusha through beautiful Maasai steppe landscapes.",
      elevation: "1,700m → 1,400m",
      distance: "Drive 6-7 hours",
      duration: "6-7 hours",
      meals: "Breakfast, Lunch",
    },
  ],
};

// ============================================
// SAFARI PACKAGES ITINERARY DATA
// ============================================

const safariItineraries: Record<string, {
  day: number;
  title: string;
  description: string;
  accommodation?: string;
  meals?: string;
  location?: string;
  image?: string;
  highlights?: string[];
  isFeatured?: boolean;
}[]> = {
  // 4 Day Safari Adventure
  "4-day-safari-adventure-in-tanzania": [
    {
      day: 1,
      title: "Arusha to Tarangire National Park",
      description: "After breakfast, depart Arusha and drive to Tarangire National Park, famous for its large elephant herds and ancient baobab trees. Enjoy a full day game drive spotting lions, leopards, zebras, wildebeest, and over 500 bird species. The park's diverse landscapes include swamps, savannah, and woodland.",
      accommodation: "Tarangire Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-elephants.jpg",
      highlights: ["Giant elephant herds", "Ancient baobab trees", "Over 500 bird species", "Lion and leopard sightings"],
      isFeatured: true,
    },
    {
      day: 2,
      title: "Tarangire to Lake Manyara National Park",
      description: "Morning game drive in Tarangire before heading to Lake Manyara National Park. This compact park is known for its tree-climbing lions, flamingos on the alkaline lake, and diverse habitats from groundwater forests to the Rift Valley escarpment.",
      accommodation: "Lake Manyara Serena Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-flamingos.jpg",
      highlights: ["Tree-climbing lions", "Pink flamingos", "Groundwater forest", "Rift Valley views"],
    },
    {
      day: 3,
      title: "Lake Manyara to Ngorongoro Crater",
      description: "Descend 600 meters into the Ngorongoro Crater, often called the 'Eighth Wonder of the World'. This UNESCO World Heritage Site hosts the highest density of wildlife in Africa, including the Big Five. Excellent chances to spot the endangered black rhino.",
      accommodation: "Ngorongoro Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-crater.jpg",
      highlights: ["UNESCO World Heritage Site", "All Big Five possible", "Black rhino sightings", "Highest wildlife density"],
      isFeatured: true,
    },
    {
      day: 4,
      title: "Ngorongoro to Arusha",
      description: "Enjoy an early morning crater tour or optional Maasai village visit. After brunch, drive back to Arusha with stops at local craft markets. Arrive in time for your onward journey.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro to Arusha",
      image: "/images/safaris/maasai-village.jpg",
      highlights: ["Maasai cultural visit", "Local craft markets", "Final game viewing"],
    },
  ],

  // 9 Days Tanzania Wildlife Safari
  "9-days-tanzania-wildlife-safari": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "Arrive at Kilimanjaro International Airport. Meet our representative and transfer to your hotel in Arusha. Evening briefing about your upcoming safari adventure.",
      accommodation: "Arusha Coffee Lodge or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/arusha-arrival.jpg",
      highlights: ["Airport meet and greet", "Safari briefing", "Welcome dinner"],
    },
    {
      day: 2,
      title: "Arusha to Tarangire National Park",
      description: "Drive to Tarangire, home to Tanzania's largest elephant population. Game drive through baobab-studded savannah, watching elephants, lions, and hundreds of bird species.",
      accommodation: "Tarangire Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-elephants.jpg",
      highlights: ["Largest elephant population", "Ancient baobab forest", "500+ bird species"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Full Day in Tarangire",
      description: "Full day exploring Tarangire's diverse ecosystems. Track lion prides, leopards in acacia trees, and massive elephant herds at the Tarangire River.",
      accommodation: "Tarangire Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-lions.jpg",
      highlights: ["Lion pride tracking", "Leopard sightings", "Elephant herds at river"],
    },
    {
      day: 4,
      title: "Tarangire to Serengeti via Ngorongoro",
      description: "Drive through the Ngorongoro Conservation Area to the Serengeti. Stop at Olduvai Gorge, the 'Cradle of Mankind'. Enter the endless plains of the Serengeti for afternoon game drive.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/olduvai-gorge.jpg",
      highlights: ["Olduvai Gorge museum", "Cradle of Mankind", "Serengeti endless plains"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Full Day in Serengeti",
      description: "Full day game drives in the Serengeti. Follow predators on the hunt, witness river crossings during migration season, and explore kopjes where lions rest.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-migration.jpg",
      highlights: ["Predator tracking", "Migration river crossings", "Lions on kopjes"],
      isFeatured: true,
    },
    {
      day: 6,
      title: "Central to Northern Serengeti",
      description: "Drive to the northern Serengeti, closer to migration routes. Visit the Mara River area, famous for dramatic wildebeest crossings. Evening sundowner.",
      accommodation: "Serengeti Migration Camp or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Northern Serengeti",
      image: "/images/safaris/mara-river-crossing.jpg",
      highlights: ["Mara River crossings", "Wildebeest migration", "Sundowner drinks"],
      isFeatured: true,
    },
    {
      day: 7,
      title: "Northern Serengeti to Ngorongoro",
      description: "Morning game drive before departing for Ngorongoro. Afternoon visit to a Maasai boma to learn about traditional culture.",
      accommodation: "Ngorongoro Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/maasai-boma.jpg",
      highlights: ["Final Serengeti game drive", "Maasai village visit", "Cultural immersion"],
    },
    {
      day: 8,
      title: "Ngorongoro Crater Floor",
      description: "Descend into the crater for a full day game drive. Spot all Big Five in this concentrated wildlife haven. Picnic lunch by the hippo pool.",
      accommodation: "Ngorongoro Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-crater.jpg",
      highlights: ["All Big Five", "Black rhino sightings", "Hippo pool picnic"],
      isFeatured: true,
    },
    {
      day: 9,
      title: "Ngorongoro to Arusha - Departure",
      description: "Morning crater rim walk or final game viewing. Drive back to Arusha with stops at craft markets. Transfer to airport for departure.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro to Arusha",
      image: "/images/safaris/crater-rim-walk.jpg",
      highlights: ["Crater rim walk", "Craft market shopping", "Airport transfer"],
    },
  ],

  // 6 Days Lodge Safari
  "6-days-tanzania-lodge-and-luxury-tented-camp-safaritarangire-lake-manyara-serengeti-ngorongoro-crater": [
    {
      day: 1,
      title: "Arrival - Arusha",
      description: "Arrive at Kilimanjaro Airport and transfer to your lodge in Arusha. Meet your guide for safari briefing and overnight stay.",
      accommodation: "Arusha Coffee Lodge or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/arusha-coffee-lodge.jpg",
      highlights: ["Luxury lodge welcome", "Safari briefing", "Rest and preparation"],
    },
    {
      day: 2,
      title: "Arusha to Tarangire National Park",
      description: "Morning departure to Tarangire National Park. Game drive among giant baobabs and elephant herds. Watch lions, leopards, and countless birds.",
      accommodation: "Tarangire Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-baobabs.jpg",
      highlights: ["Giant baobab trees", "Elephant herds", "Big cat sightings"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Tarangire to Lake Manyara",
      description: "Drive to Lake Manyara National Park. Afternoon game drive to see tree-climbing lions, hippos, flamingos, and the diverse forest ecosystem.",
      accommodation: "Lake Manyara Serena Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-lions.jpg",
      highlights: ["Tree-climbing lions", "Flamingo colonies", "Groundwater forest"],
    },
    {
      day: 4,
      title: "Lake Manyara to Serengeti",
      description: "Cross the Ngorongoro Highlands to the Serengeti. Stop at Olduvai Gorge. Afternoon game drive on the endless plains.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-plains.jpg",
      highlights: ["Olduvai Gorge visit", "Endless Serengeti plains", "Big cat territory"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Serengeti to Ngorongoro",
      description: "Morning game drive in the Serengeti before driving to Ngorongoro. Afternoon at leisure enjoying crater rim views.",
      accommodation: "Ngorongoro Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-rim.jpg",
      highlights: ["Final Serengeti game drive", "Spectacular crater views", "Luxury rim lodge"],
    },
    {
      day: 6,
      title: "Ngorongoro Crater - Departure",
      description: "Early descent into Ngorongoro Crater for game drive. Picnic lunch in the crater. Drive back to Arusha for departure.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater to Arusha",
      image: "/images/safaris/ngorongoro-floor.jpg",
      highlights: ["Crater floor game drive", "Big Five sightings", "Picnic lunch"],
      isFeatured: true,
    },
  ],

  // 3 Days Lodge Safari
  "3-days-tanzania-lodge-safari-tarangire-lake-manyara-ngorongoro-crater": [
    {
      day: 1,
      title: "Arusha to Tarangire & Lake Manyara",
      description: "Depart Arusha for Tarangire National Park. Game drive among elephants and baobabs. Continue to Lake Manyara area for overnight.",
      accommodation: "Lake Manyara Serena Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire & Lake Manyara",
      image: "/images/safaris/tarangire-elephants.jpg",
      highlights: ["Elephant encounters", "Baobab landscapes", "Two parks in one day"],
      isFeatured: true,
    },
    {
      day: 2,
      title: "Lake Manyara to Ngorongoro",
      description: "Morning game drive at Lake Manyara. Drive to Ngorongoro Conservation Area. Optional Maasai village visit. Sunset views of the crater.",
      accommodation: "Ngorongoro Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara & Ngorongoro",
      image: "/images/safaris/lake-manyara-flamingos.jpg",
      highlights: ["Tree-climbing lions", "Maasai village", "Crater sunset views"],
    },
    {
      day: 3,
      title: "Ngorongoro Crater - Departure",
      description: "Descend into the crater for a full morning game drive. Spot rhinos, lions, elephants, and buffalos. Return to Arusha.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-rhino.jpg",
      highlights: ["Black rhino sightings", "Big Five possible", "UNESCO World Heritage"],
      isFeatured: true,
    },
  ],

  // 6 Days Budget Camping Safari
  "6-days-5-nights-budget-camping-safari-tarangire-lake-manyara-serengeti-and-ngorongoro-crater": [
    {
      day: 1,
      title: "Arusha to Tarangire National Park",
      description: "Depart Arusha and drive to Tarangire. Full day game viewing among elephants, lions, and ancient baobab trees.",
      accommodation: "Tarangire Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/camping-tarangire.jpg",
      highlights: ["Budget-friendly camping", "Elephant encounters", "Authentic bush experience"],
      isFeatured: true,
    },
    {
      day: 2,
      title: "Tarangire to Lake Manyara",
      description: "Morning game drive, then proceed to Lake Manyara National Park. Afternoon game drive to see tree-climbing lions and flamingos.",
      accommodation: "Lake Manyara Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-hippos.jpg",
      highlights: ["Tree-climbing lions", "Flamingo flocks", "Hippo pools"],
    },
    {
      day: 3,
      title: "Lake Manyara to Serengeti",
      description: "Drive through the highlands to the Serengeti. Visit Olduvai Gorge. Evening game drive as predators become active.",
      accommodation: "Serengeti Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-sunset.jpg",
      highlights: ["Olduvai Gorge history", "Evening predator activity", "Bush camping"],
      isFeatured: true,
    },
    {
      day: 4,
      title: "Full Day in Serengeti",
      description: "Full day exploring the Serengeti's diverse ecosystems. Search for the Big Five and witness the endless plains.",
      accommodation: "Serengeti Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-lions.jpg",
      highlights: ["Big Five search", "Endless plains", "Predator tracking"],
    },
    {
      day: 5,
      title: "Serengeti to Ngorongoro",
      description: "Morning game drive before driving to Ngorongoro Conservation Area. Afternoon cultural visit or crater rim walk.",
      accommodation: "Simba Campsite, Ngorongoro",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/simba-campsite.jpg",
      highlights: ["Crater rim camping", "Cultural experience", "Star-filled nights"],
    },
    {
      day: 6,
      title: "Ngorongoro Crater - Departure",
      description: "Early morning crater descent for game drive. Return to Arusha in the afternoon.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-crater.jpg",
      highlights: ["Crater floor wildlife", "Big Five sightings", "UNESCO heritage"],
      isFeatured: true,
    },
  ],

  // 7 Days Tented Camp Safari
  "7-days-tanzania-tented-camp-safari": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "Welcome to Tanzania! Transfer from Kilimanjaro Airport to your Arusha accommodation. Evening briefing with your safari guide.",
      accommodation: "Arusha Planet Lodge or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/arusha-arrival.jpg",
      highlights: ["Warm welcome", "Safari briefing", "Rest and preparation"],
    },
    {
      day: 2,
      title: "Arusha to Tarangire National Park",
      description: "Drive to Tarangire, famous for huge elephant herds and iconic baobab trees. Full day of game viewing.",
      accommodation: "Tarangire Tented Camp",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tented-camp-tarangire.jpg",
      highlights: ["Luxury tented camping", "Huge elephant herds", "Iconic baobabs"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Tarangire to Serengeti National Park",
      description: "Journey through the Ngorongoro Conservation Area to the Serengeti. Stop at Olduvai Gorge. Afternoon game drive.",
      accommodation: "Serengeti Tented Camp",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-tented.jpg",
      highlights: ["Scenic highlands drive", "Olduvai Gorge", "Serengeti arrival"],
    },
    {
      day: 4,
      title: "Full Day in Serengeti",
      description: "Explore the Serengeti from dawn to dusk. Follow the great migration, track big cats, and enjoy the endless plains.",
      accommodation: "Serengeti Tented Camp",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-migration.jpg",
      highlights: ["Great Migration", "Big cat tracking", "Dawn to dusk game drives"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Serengeti to Central Serengeti",
      description: "Move to a different area of the Serengeti for varied wildlife experiences. Evening sundowner drinks.",
      accommodation: "Serengeti Tented Camp",
      meals: "Breakfast, Lunch, Dinner",
      location: "Central Serengeti",
      image: "/images/safaris/serengeti-sundowner.jpg",
      highlights: ["Varied landscapes", "Sundowner experience", "New wildlife areas"],
    },
    {
      day: 6,
      title: "Serengeti to Ngorongoro",
      description: "Final morning game drive, then drive to Ngorongoro Crater rim. Spectacular views into the crater.",
      accommodation: "Ngorongoro Tented Camp",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-rim-tent.jpg",
      highlights: ["Crater rim views", "Tented comfort", "Wildlife silhouettes"],
    },
    {
      day: 7,
      title: "Ngorongoro Crater - Departure",
      description: "Descend into the crater for a half-day game drive. Return to Arusha for your departure flight.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-floor.jpg",
      highlights: ["Crater floor game drive", "Big Five finale", "Departure transfer"],
      isFeatured: true,
    },
  ],

  // 5 Days Luxury Safari
  "5-days-tanzania-luxury-safarilake-manyara-serengeti-ngorongoro": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "VIP arrival at Kilimanjaro Airport. Private transfer to luxury accommodation in Arusha. Welcome dinner with wine pairing.",
      accommodation: "The Arusha Hotel or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/luxury-arrival.jpg",
      highlights: ["VIP airport welcome", "Luxury accommodation", "Wine-paired dinner"],
    },
    {
      day: 2,
      title: "Arusha to Lake Manyara",
      description: "Private game drive at Lake Manyara. Seek out tree-climbing lions and flocks of flamingos. Sundowner drinks at the lodge.",
      accommodation: "&Beyond Lake Manyara Tree Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-treehouse.jpg",
      highlights: ["Tree Lodge experience", "Private game drive", "Sundowner drinks"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Lake Manyara to Serengeti",
      description: "Scenic flight to the Serengeti (optional) or private drive. Afternoon game drive following the Big Five.",
      accommodation: "Four Seasons Safari Lodge Serengeti or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/four-seasons-serengeti.jpg",
      highlights: ["Optional scenic flight", "Four Seasons luxury", "Big Five tracking"],
      isFeatured: true,
    },
    {
      day: 4,
      title: "Full Day in Serengeti",
      description: "Private full-day safari with exclusive picnic lunch on the plains. Hot air balloon safari optional.",
      accommodation: "Four Seasons Safari Lodge Serengeti or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/hot-air-balloon.jpg",
      highlights: ["Hot air balloon option", "Exclusive picnic lunch", "Private safari vehicle"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Serengeti to Ngorongoro - Departure",
      description: "Fly or drive to Ngorongoro for a private crater tour. Champagne lunch in the crater. Transfer to Arusha/Kilimanjaro Airport.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/champagne-crater.jpg",
      highlights: ["Champagne crater lunch", "Private crater tour", "VIP departure"],
      isFeatured: true,
    },
  ],

  // 3 Days Budget Camping Safari
  "3-days-tanzania-budget-camping-safari-tarangire-lake-manyara-and-ngorongoro-crater": [
    {
      day: 1,
      title: "Arusha to Tarangire & Lake Manyara",
      description: "Morning game drive in Tarangire among elephants. Afternoon at Lake Manyara seeing tree-climbing lions and flamingos.",
      accommodation: "Lake Manyara Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire & Lake Manyara",
      image: "/images/safaris/budget-camping.jpg",
      highlights: ["Two parks in one day", "Elephant encounters", "Budget camping"],
      isFeatured: true,
    },
    {
      day: 2,
      title: "Lake Manyara to Ngorongoro",
      description: "Drive to Ngorongoro Conservation Area. Afternoon visit to a Maasai village or crater rim walk.",
      accommodation: "Simba Campsite, Ngorongoro",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/maasai-cultural.jpg",
      highlights: ["Maasai village visit", "Crater rim walk", "Authentic camping"],
    },
    {
      day: 3,
      title: "Ngorongoro Crater - Departure",
      description: "Early morning crater descent. Half-day game drive seeking rhinos and lions. Return to Arusha.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-rhino.jpg",
      highlights: ["Black rhino search", "Crater wildlife", "Big Five opportunity"],
      isFeatured: true,
    },
  ],

  // 6 Days Safari to Tarangire, Ngorongoro & Serengeti
  "6-days-safari-to-tarangire-ngorongoro-serengeti-central-north": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "Arrive at Kilimanjaro Airport. Transfer to Arusha for overnight and safari briefing.",
      accommodation: "Arusha Coffee Lodge or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/arusha-lodge.jpg",
      highlights: ["Airport transfer", "Safari briefing", "Welcome dinner"],
    },
    {
      day: 2,
      title: "Arusha to Tarangire",
      description: "Full day game drive in Tarangire National Park. Large elephant herds and baobab trees create iconic African scenes.",
      accommodation: "Tarangire Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-elephants.jpg",
      highlights: ["Large elephant herds", "Iconic baobabs", "Full day game drive"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Tarangire to Ngorongoro",
      description: "Drive to Ngorongoro Conservation Area. Afternoon crater rim walk and sunset views.",
      accommodation: "Ngorongoro Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-sunset.jpg",
      highlights: ["Crater rim walk", "Spectacular sunsets", "Luxury lodge"],
    },
    {
      day: 4,
      title: "Ngorongoro to Serengeti",
      description: "Early crater descent for game drive. Picnic lunch in the crater. Continue to Serengeti via Olduvai Gorge.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/ngorongoro-floor.jpg",
      highlights: ["Crater floor game drive", "Olduvai Gorge", "Serengeti arrival"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Full Day in Serengeti",
      description: "Full day exploring the Serengeti's central and northern areas. Search for migration herds and big cats.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-cats.jpg",
      highlights: ["Migration herds", "Big cat territory", "Central & northern areas"],
      isFeatured: true,
    },
    {
      day: 6,
      title: "Serengeti to Arusha - Departure",
      description: "Morning game drive before flying or driving back to Arusha. Transfer to airport.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Serengeti to Arusha",
      image: "/images/safaris/serengeti-sunrise.jpg",
      highlights: ["Final game drive", "Flight option", "Airport transfer"],
    },
  ],

  // 8 Days Wonders of Tanzania
  "8-days-wonders-of-tanzania-safari": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "Welcome to Tanzania! Transfer from airport to hotel. Evening safari briefing.",
      accommodation: "Mount Meru Hotel or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/mount-meru-hotel.jpg",
      highlights: ["Warm welcome", "Safari briefing", "Mount Meru views"],
    },
    {
      day: 2,
      title: "Arusha to Tarangire",
      description: "Drive to Tarangire. Full day game viewing among elephant herds and ancient baobabs.",
      accommodation: "Tarangire Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-elephants.jpg",
      highlights: ["Massive elephant herds", "Ancient baobab trees", "Full day game drive"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Tarangire to Lake Manyara",
      description: "Morning game drive, then transfer to Lake Manyara. Afternoon game drive to see tree-climbing lions.",
      accommodation: "Lake Manyara Serena Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-lions.jpg",
      highlights: ["Tree-climbing lions", "Flamingo colonies", "Diverse habitats"],
    },
    {
      day: 4,
      title: "Lake Manyara to Serengeti",
      description: "Cross the Ngorongoro Highlands. Visit Olduvai Gorge. Enter the Serengeti for evening game drive.",
      accommodation: "Serengeti Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/olduvai-gorge.jpg",
      highlights: ["Olduvai Gorge history", "Highland scenery", "Serengeti arrival"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Full Day in Serengeti - Central",
      description: "Explore Seronera Valley, the heart of the Serengeti. Prime predator territory with river crossings.",
      accommodation: "Serengeti Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Central Serengeti",
      image: "/images/safaris/seronera-valley.jpg",
      highlights: ["Seronera Valley predators", "River crossings", "Heart of Serengeti"],
      isFeatured: true,
    },
    {
      day: 6,
      title: "Serengeti - Northern Extension",
      description: "Drive to northern Serengeti. Visit Mara River area during migration season. Remote wilderness experience.",
      accommodation: "Serengeti Migration Camp or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Northern Serengeti",
      image: "/images/safaris/mara-river.jpg",
      highlights: ["Mara River drama", "Migration season", "Remote wilderness"],
      isFeatured: true,
    },
    {
      day: 7,
      title: "Serengeti to Ngorongoro",
      description: "Final Serengeti game drive before heading to Ngorongoro. Maasai cultural visit.",
      accommodation: "Ngorongoro Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/maasai-village.jpg",
      highlights: ["Final Serengeti safari", "Maasai culture", "Crater rim views"],
    },
    {
      day: 8,
      title: "Ngorongoro Crater - Departure",
      description: "Descend into the crater for game viewing. Return to Arusha for departure.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-floor.jpg",
      highlights: ["Crater floor game drive", "Big Five opportunity", "Farewell Tanzania"],
      isFeatured: true,
    },
  ],

  // 4 Days Safari to Ngorongoro and Serengeti
  "4-days-safari-to-ngorongoro-and-serengeti": [
    {
      day: 1,
      title: "Arusha to Ngorongoro",
      description: "Drive to Ngorongoro Conservation Area. Afternoon visit to Maasai village. Sunset views of the crater.",
      accommodation: "Ngorongoro Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-sunset.jpg",
      highlights: ["Maasai village visit", "Crater sunset views", "Cultural immersion"],
    },
    {
      day: 2,
      title: "Ngorongoro to Serengeti",
      description: "Early descent into Ngorongoro Crater for game drive. Picnic lunch. Continue to Serengeti via Olduvai Gorge.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/ngorongoro-descent.jpg",
      highlights: ["Crater game drive", "Olduvai Gorge museum", "Serengeti plains"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Full Day in Serengeti",
      description: "Full day game drives following predators, migration herds, and the endless plains.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-cheetah.jpg",
      highlights: ["Predator tracking", "Migration herds", "Endless plains"],
      isFeatured: true,
    },
    {
      day: 4,
      title: "Serengeti to Arusha - Departure",
      description: "Morning game drive. Drive or fly back to Arusha. Transfer to airport.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Serengeti to Arusha",
      image: "/images/safaris/serengeti-sunrise.jpg",
      highlights: ["Final game drive", "Flight option available", "Airport transfer"],
    },
  ],

  // 6 Days Migration Safari
  "6-days-tanzania-migration-safari-ndutu-manyara-serengeti-ngorongoro-crater": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "Arrive at Kilimanjaro Airport. Transfer to Arusha accommodation. Safari briefing.",
      accommodation: "Gran Melia Arusha or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/gran-melia-arusha.jpg",
      highlights: ["Luxury arrival", "Safari briefing", "5-star comfort"],
    },
    {
      day: 2,
      title: "Arusha to Lake Manyara",
      description: "Drive to Lake Manyara National Park. Game drive to see tree-climbing lions, flamingos, and hippos.",
      accommodation: "Lake Manyara Serena Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-flamingos.jpg",
      highlights: ["Tree-climbing lions", "Flamingo spectacle", "Hippo encounters"],
    },
    {
      day: 3,
      title: "Lake Manyara to Ndutu (Southern Serengeti)",
      description: "Drive to Ndutu area during calving season (Dec-Mar). Witness thousands of wildebeest giving birth.",
      accommodation: "Ndutu Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ndutu Area, Serengeti",
      image: "/images/safaris/ndutu-calving.jpg",
      highlights: ["Calving season", "Wildebeest births", "Predator action"],
      isFeatured: true,
    },
    {
      day: 4,
      title: "Full Day Migration Tracking",
      description: "Full day following the migration herds. Watch predators hunting calves. Incredible wildlife density.",
      accommodation: "Ndutu Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ndutu Area, Serengeti",
      image: "/images/safaris/migration-hunt.jpg",
      highlights: ["Predator hunting", "Massive herds", "Wildlife density"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Ndutu to Ngorongoro",
      description: "Morning game drive in Ndutu. Drive to Ngorongoro Conservation Area for sunset crater views.",
      accommodation: "Ngorongoro Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-rim-sunset.jpg",
      highlights: ["Final Ndutu drive", "Crater rim sunset", "Luxury lodge"],
    },
    {
      day: 6,
      title: "Ngorongoro Crater - Departure",
      description: "Descend into the crater for game drive. Return to Arusha for departure.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-crater.jpg",
      highlights: ["Crater floor wildlife", "Big Five finale", "Departure"],
      isFeatured: true,
    },
  ],

  // 2 Days Lodge Safari
  "2-days-tanzania-lodge-safari": [
    {
      day: 1,
      title: "Arusha to Lake Manyara",
      description: "Drive to Lake Manyara National Park. Full day game drive to see tree-climbing lions, elephants, giraffes, and pink flamingos on the alkaline lake.",
      accommodation: "Lake Manyara Serena Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-game-drive.jpg",
      highlights: ["Tree-climbing lions", "Pink flamingos", "Elephants and giraffes"],
      isFeatured: true,
    },
    {
      day: 2,
      title: "Lake Manyara to Ngorongoro - Departure",
      description: "Drive to Ngorongoro Crater. Descend into the crater for a half-day game drive seeking rhinos, lions, and elephants. Return to Arusha.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-crater.jpg",
      highlights: ["Crater floor wildlife", "Black rhino sightings", "Big Five opportunity"],
      isFeatured: true,
    },
  ],

  // 5 Days Budget Camping Safari
  "5-days-4-nights-budget-camping-safari-lake-manyara-serengeti-and-ngorongoro": [
    {
      day: 1,
      title: "Arusha to Lake Manyara",
      description: "Depart Arusha for Lake Manyara National Park. Afternoon game drive among tree-climbing lions and flamingos.",
      accommodation: "Lake Manyara Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Lake Manyara National Park",
      image: "/images/safaris/lake-manyara-camping.jpg",
      highlights: ["Budget camping adventure", "Tree-climbing lions", "Flamingo flocks"],
    },
    {
      day: 2,
      title: "Lake Manyara to Serengeti",
      description: "Drive to Serengeti through Ngorongoro. Visit Olduvai Gorge. Evening game drive on the plains.",
      accommodation: "Serengeti Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-camping.jpg",
      highlights: ["Olduvai Gorge", "Evening game drive", "Bush camping"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Full Day in Serengeti",
      description: "Full day exploring the Serengeti. Track big cats, elephants, and witness the endless herds.",
      accommodation: "Serengeti Public Campsite",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-wildlife.jpg",
      highlights: ["Big cat tracking", "Elephant herds", "Endless plains"],
      isFeatured: true,
    },
    {
      day: 4,
      title: "Serengeti to Ngorongoro",
      description: "Morning game drive. Drive to Ngorongoro Conservation Area for overnight at crater rim.",
      accommodation: "Simba Campsite, Ngorongoro",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/simba-campsite.jpg",
      highlights: ["Crater rim camping", "Stargazing", "Wildlife sounds"],
    },
    {
      day: 5,
      title: "Ngorongoro Crater - Departure",
      description: "Early descent into the crater. Game drive seeking all Big Five. Return to Arusha.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/ngorongoro-floor.jpg",
      highlights: ["All Big Five possible", "Crater floor game drive", "Amazing value"],
      isFeatured: true,
    },
  ],

  // Walking Safari & Trekking on Ngorongoro
  "walking-safari-trekking-on-ngorongoro": [
    {
      day: 1,
      title: "Arusha to Ngorongoro",
      description: "Drive to Ngorongoro Conservation Area. Afternoon orientation walk on the crater rim with armed ranger. Stunning views into the caldera.",
      accommodation: "Ngorongoro Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-rim-walk.jpg",
      highlights: ["Crater rim walking", "Armed ranger escort", "Caldera views"],
    },
    {
      day: 2,
      title: "Crater Floor Walking Safari",
      description: "Descend into the crater for a unique walking safari with Maasai guides and armed rangers. Walk among zebras, wildebeest, and if lucky, rhinos. Game drive to complement walking.",
      accommodation: "Ngorongoro Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Crater",
      image: "/images/safaris/walking-safari.jpg",
      highlights: ["Walking among wildlife", "Maasai guides", "Unique crater experience"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Empakaai Crater Trek - Departure",
      description: "Drive to Empakaai Crater. Trek down to the crater lake filled with flamingos. Stunning views of Ol Doinyo Lengai. Return to Arusha.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Empakaai Crater",
      image: "/images/safaris/empakaai-crater.jpg",
      highlights: ["Empakaai flamingos", "Ol Doinyo Lengai views", "Off-beaten-path trek"],
      isFeatured: true,
    },
  ],

  // 7 Days Serval Wildlife Safari
  "7-days-safari-to-tanzania-serval-wildlife": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "Arrive at Kilimanjaro Airport. Transfer to Arusha. Safari briefing focusing on rare wildlife sightings.",
      accommodation: "The African Tulip Hotel or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/african-tulip.jpg",
      highlights: ["Specialist briefing", "Rare wildlife focus", "Expert guides"],
    },
    {
      day: 2,
      title: "Arusha to Tarangire",
      description: "Drive to Tarangire. Specialized game drive seeking servals, African wild cats, and rare antelope species.",
      accommodation: "Tarangire Treetops or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-serval.jpg",
      highlights: ["Serval sightings", "African wild cats", "Rare antelope"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Tarangire Full Day",
      description: "Full day exploring Tarangire's varied habitats. Night drive to spot nocturnal predators including servals.",
      accommodation: "Tarangire Treetops or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/night-drive.jpg",
      highlights: ["Night game drive", "Nocturnal predators", "Unique experience"],
      isFeatured: true,
    },
    {
      day: 4,
      title: "Tarangire to Serengeti",
      description: "Drive to Serengeti. Focus on finding rare species like aardvark, honey badger, and African wild dog.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/wild-dog.jpg",
      highlights: ["African wild dog search", "Honey badger", "Rare sightings"],
    },
    {
      day: 5,
      title: "Serengeti - Specialized Wildlife",
      description: "Expert-guided game drives focusing on predator behavior and rare wildlife. Early morning and late evening drives.",
      accommodation: "Serengeti Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/predator-behavior.jpg",
      highlights: ["Predator behavior study", "Dawn and dusk drives", "Expert naturalist"],
      isFeatured: true,
    },
    {
      day: 6,
      title: "Serengeti to Ngorongoro",
      description: "Morning game drive. Drive to Ngorongoro. Crater rim walk at dusk seeking spotted hyenas.",
      accommodation: "Ngorongoro Serena Safari Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/spotted-hyena.jpg",
      highlights: ["Spotted hyena tracking", "Dusk rim walk", "Unique behaviors"],
    },
    {
      day: 7,
      title: "Ngorongoro Crater - Departure",
      description: "Dawn crater descent. Last chance for black rhino and golden jackal sightings. Return to Arusha.",
      accommodation: "End of safari",
      meals: "Breakfast, Lunch",
      location: "Ngorongoro Crater",
      image: "/images/safaris/black-rhino.jpg",
      highlights: ["Black rhino sightings", "Golden jackal", "Wildlife specialist finale"],
      isFeatured: true,
    },
  ],

  // 10 Day Adventure Safari & Zanzibar
  "10-day-adventure-in-tanzania-safari-zanzibar": [
    {
      day: 1,
      title: "Arrival in Arusha",
      description: "Welcome to Tanzania! Transfer from Kilimanjaro Airport to your Arusha hotel. Rest and safari briefing.",
      accommodation: "Mount Meru Hotel or similar",
      meals: "Dinner",
      location: "Arusha",
      image: "/images/safaris/arusha-welcome.jpg",
      highlights: ["Tanzania welcome", "Safari briefing", "Mount Meru views"],
    },
    {
      day: 2,
      title: "Arusha to Tarangire",
      description: "Drive to Tarangire National Park. Game drive among giant elephants and ancient baobab trees.",
      accommodation: "Tarangire Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Tarangire National Park",
      image: "/images/safaris/tarangire-elephants.jpg",
      highlights: ["Giant elephants", "Ancient baobabs", "Incredible birdlife"],
      isFeatured: true,
    },
    {
      day: 3,
      title: "Tarangire to Serengeti",
      description: "Journey to the Serengeti via Ngorongoro highlands and Olduvai Gorge. Afternoon game drive.",
      accommodation: "Serengeti Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/olduvai-gorge.jpg",
      highlights: ["Olduvai Gorge history", "Highland scenery", "Serengeti plains"],
    },
    {
      day: 4,
      title: "Full Day in Serengeti",
      description: "Full day exploring the endless plains. Follow migration herds and big cats.",
      accommodation: "Serengeti Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Serengeti National Park",
      image: "/images/safaris/serengeti-migration.jpg",
      highlights: ["Migration herds", "Big cat tracking", "Endless plains"],
      isFeatured: true,
    },
    {
      day: 5,
      title: "Serengeti to Ngorongoro",
      description: "Morning game drive. Transfer to Ngorongoro for sunset views over the crater.",
      accommodation: "Ngorongoro Sopa Lodge or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Ngorongoro Conservation Area",
      image: "/images/safaris/ngorongoro-sunset.jpg",
      highlights: ["Final Serengeti drive", "Crater sunset", "Spectacular views"],
    },
    {
      day: 6,
      title: "Ngorongoro to Arusha - Fly to Zanzibar",
      description: "Early crater descent for game drive. Drive to Arusha and fly to Zanzibar.",
      accommodation: "Zanzibar Beach Resort or similar",
      meals: "Breakfast, Lunch, Dinner",
      location: "Zanzibar",
      image: "/images/safaris/zanzibar-arrival.jpg",
      highlights: ["Crater game drive", "Flight to Zanzibar", "Beach paradise awaits"],
      isFeatured: true,
    },
    {
      day: 7,
      title: "Zanzibar - Beach & Spice Tour",
      description: "Morning spice tour in the plantations. Afternoon at leisure on pristine beaches.",
      accommodation: "Zanzibar Beach Resort or similar",
      meals: "Breakfast, Dinner",
      location: "Zanzibar",
      image: "/images/safaris/zanzibar-spice-tour.jpg",
      highlights: ["Famous spice tour", "Pristine beaches", "Island relaxation"],
    },
    {
      day: 8,
      title: "Zanzibar - Stone Town",
      description: "Tour UNESCO World Heritage Stone Town. Visit the old slave market, Sultan's Palace, and labyrinthine streets.",
      accommodation: "Zanzibar Beach Resort or similar",
      meals: "Breakfast, Dinner",
      location: "Zanzibar",
      image: "/images/safaris/stone-town.jpg",
      highlights: ["UNESCO World Heritage", "Historic architecture", "Cultural immersion"],
      isFeatured: true,
    },
    {
      day: 9,
      title: "Zanzibar - Beach Day",
      description: "Full day at leisure. Optional water sports, dolphin tour, or snorkeling at Mnemba Atoll.",
      accommodation: "Zanzibar Beach Resort or similar",
      meals: "Breakfast, Dinner",
      location: "Zanzibar",
      image: "/images/safaris/zanzibar-beach.jpg",
      highlights: ["Mnemba snorkeling", "Dolphin tours", "Water sports"],
    },
    {
      day: 10,
      title: "Zanzibar - Departure",
      description: "Morning at leisure. Transfer to Zanzibar airport for departure flight.",
      accommodation: "End of trip",
      meals: "Breakfast",
      location: "Zanzibar",
      image: "/images/safaris/zanzibar-farewell.jpg",
      highlights: ["Final beach time", "Island memories", "Safari & beach complete"],
    },
  ],
};

// ============================================
// MAIN SEEDING FUNCTION
// ============================================

async function seedItineraries() {
  console.log("🌱 Seeding itinerary data...\n");

  // Seed Trekking Routes
  console.log("🏔️ Updating Trekking Routes...");
  for (const [slug, itinerary] of Object.entries(trekkingItineraries)) {
    try {
      const route = await prisma.trekkingRoute.findFirst({
        where: {
          OR: [
            { slug },
            { slug: slug.replace(/-/g, "-") },
          ],
        },
      });

      if (route) {
        await prisma.trekkingRoute.update({
          where: { id: route.id },
          data: { itinerary },
        });
        console.log(`  ✅ Updated: ${route.title}`);
      } else {
        console.log(`  ⚠️ Route not found: ${slug}`);
      }
    } catch (error) {
      console.error(`  ❌ Error updating ${slug}:`, error);
    }
  }

  // Seed Safari Packages
  console.log("\n🦁 Updating Safari Packages...");
  for (const [slug, itinerary] of Object.entries(safariItineraries)) {
    try {
      const safari = await prisma.safariPackage.findFirst({
        where: {
          OR: [
            { slug },
            { slug: { contains: slug.split("-").slice(0, 4).join("-") } },
          ],
        },
      });

      if (safari) {
        await prisma.safariPackage.update({
          where: { id: safari.id },
          data: { itinerary },
        });
        console.log(`  ✅ Updated: ${safari.title}`);
      } else {
        console.log(`  ⚠️ Safari not found: ${slug}`);
      }
    } catch (error) {
      console.error(`  ❌ Error updating ${slug}:`, error);
    }
  }

  console.log("\n✅ Itinerary seeding complete!");
}

// Run the seeding
seedItineraries()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
